console.log ("primer paso: calentar el agua a 85 °c")
console.log ("segundo paso: colocar yerba en mate")
console.log ("inclinar mate a 45°c y acomodar yerba")
console.log ("colocar bombilla")
console.log ("agregar agua al mate y endulzar si es necesario")